print('prompt engineering playground')
user_question = 'spi communication is working properly, what changes to do now to increase the speed?'

#Ask the model to do something without giving it an example.[zsp]
zero_shot_prompt = user_question 
#print(zero_shot_prompt)

#few shot prompting
few_Shot_prompt = '''
Example 1:
Problem: SPI timeout occurred.
Answer: Check SPI clock, wiring, and timeout configuration.

Example 2:
Problem: SPI CRC error occurred.
Answer: Check data integrity, clock configuration, and signal quality.

Now answer this problem:
spi communication is working properly, what changes to do now to increase the speed?
'''
#print(few_Shot_prompt)

#role_prompting
role_prompt = '''
role_prompt = """
You are an experienced embedded systems debugging engineer.

Analyze the following problem and explain the most likely causes
using practical engineering reasoning.

Problem:
spi communication is working properly, what changes to do now to increase the speed?
"""
'''
#print(role_prompt)


#json
json_prompt = '''
analyze this engineering question.
return only valid JSON.
use exactly these fields:

{
    
    "current_status" : "",
    "goal" : "",
    "confidence" : "",
    "risk" : "",
    "recommended_action" : ""
    
}

Question:
SPI communication is working properly. What changes should be made to increase the speed?

'''
#print(json_prompt)

#xml prompt
xml_prompt = '''
analyze this engineering question.
return the answer using exactly this xml structure:

<success>
    <current_status></current_status>
    <goal></goal>
    <confidence></confidence>
    <risk></risk>
    <recommended_action></recommended_Action>
</success>

Question:
SPI communication is working properly. What changes should be made to increase the speed?

'''
#print(xml_prompt)

#making first api call

#from openai import OpenAI  #This imports the OpenAI class from the OpenAI Python package we installed.
#client = OpenAI()  #This creates an OpenAI client.
#response = client.responses.create(   #sends a request to the LLM.
#    model = 'gpt-5.6-luna', #tells the API which model to use.
 #   input= user_question  #We're sending the question we already created earlier:
   
#)

#print(response.output_text)

#making first api call with gemini

from google import genai  #Imports Google's Gemini SDK so Python can communicate with Gemini.
import os  #Imports Python's built-in os module.

#This creates the Gemini client.
client = genai.Client(
    api_key = os.getenv("GEMINI_API_KEY")    
)

#retrieves the API key set in PowerShell.
#Google currently recommends the Interactions API for new projects
interaction = client.interactions.create(
    model="gemini-3.6-flash",
    input= xml_prompt #can change in zsp,xml,fsp
)

print("\n XML OUTPUT:") #ALSO change this when changing input
print(interaction.output_text)  #gets the text generated by Gemini.



print("\n" + "=" * 60)
print("PROMPT COMPARISON")
print("=" * 60)

print("\n1. ZERO-SHOT")
print("Direct instruction without examples.")

print("\n2. FEW-SHOT")
print("Provides examples to show the expected answer pattern.")

print("\n3. ROLE PROMPTING")
print("Defines the role and perspective the model should use.")

print("\n4. JSON STRUCTURED OUTPUT")
print("Requests machine-readable JSON with specific fields.")

print("\n5. XML OUTPUT")
print("Requests a structured XML response.")


"""
DAY 5 OBSERVATIONS

1. Zero-shot prompting
- Gives the model a direct question.
- No examples are provided.
- Useful for simple and straightforward tasks.

2. Few-shot prompting
- Provides examples before the actual question.
- Helps demonstrate the expected response pattern.
- Useful when consistency in the response format or style matters.

3. Role prompting
- Gives the model a specific role or perspective.
- Can guide the type of explanation and terminology used.
- Useful for domain-specific tasks.

4. JSON structured output
- Requests information in a machine-readable format.
- Python can parse the returned JSON.
- Useful when an application needs to consume the model output.

5. XML output
- Provides another structured output format.
- Uses tags to organize information.
- Useful when working with systems that expect XML.

6. Main learning
- Prompt engineering is about giving clear instructions and
  constraints to an LLM.
- Different prompt techniques solve different problems.
- Structured outputs are especially useful when LLM responses
  need to be used by software.
"""